name: indicator-sound-switcher
base: core18
adopt-info: indicator-sound-switcher
summary: Sound input/output selector application for Linux
title: Sound Switcher Indicator
description: |
  Sound Switcher Indicator shows an icon in the indicator area or the
  system tray (whatever is available in your desktop environment).
  The icon's menu allows you to switch the current sound input and
  output with a single click.

  The appearance of the menu can be customised. For example, devices
  and ports can be given custom display names, hidden etc.

icon: icons/indicator-sound-switcher.svg
license: GPL-3.0
grade: stable
confinement: strict

apps:
  indicator-sound-switcher:
    command: desktop-launch $SNAP/bin/launch.sh $SNAP/bin/indicator-sound-switcher
    desktop: share/applications/indicator-sound-switcher.desktop
    autostart: indicator-sound-switcher.desktop
    extensions:
      - gnome-3-28
    plugs:
      - audio-playback

parts:
  indicator-sound-switcher:
    plugin: python
    source: .
    build-packages:
      - gettext
    stage-packages:
      - gir1.2-ayatanaappindicator3-0.1
      - gir1.2-keybinder-3.0
      - libayatana-appindicator3-1
      - libayatana-indicator3-7
      - libkeybinder-3.0-0
      - python3-gi

    override-pull: |
      snapcraftctl pull

      # Use version from setup.py
      version="$(sed -ne 's/\s*APP_VERSION\s*=\s*\x27\([^\x27]\+\)\x27.*/\1/p' setup.py)"
      
      snapcraftctl set-version "$version"

      # Fix icon path in the .desktop
      sed -i -E 's!^Icon=.*!Icon=/usr/share/icons/hicolor/scalable/status/indicator-sound-switcher.svg!' indicator-sound-switcher.desktop

  resources:
    plugin: dump
    source: .
    organize:
      icons: usr/share/icons/hicolor/scalable/status
      snap/local/launch.sh: bin/
    stage:
      - usr/*
      - bin/*
